---
"on":
  workflow_call:

permissions:
  contents: read

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

env:
  HAB_LICENSE: accept-no-persist
  CHEF_LICENSE: accept-no-persist

jobs:
  rspec:
    env:
      BUNDLE_WITH: ${{ inputs.bundle_with }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install chefspec
        run: gem install chefspec
      - name: Run RSpec
        run: rspec --format documentation --color
