---
"on":
  workflow_call:

permissions:
  contents: read

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

env:
  HAB_LICENSE: accept-no-persist

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Chef
        uses: actionshub/chef-install@main
        with:
          license: ${{ vars.CHEF_LICENSE_KEY }}
          chefDownloadUrl: chefdownload-commercial.chef.io
          project: chef-workstation-enterprise
          version: latest
      - name: Run ChefSpec/RSpec unit tests
        run: |
          chef exec rspec
